/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitelinksRouteImport } from './routes/sitelinks'
import { Route as TechExpertiseRouteImport } from './routes/tech-expertise'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesBuildingCustomEnterpriseSoftwareVsSaasRouteImport } from './routes/articles.building-custom-enterprise-software-vs-saas'
import { Route as ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRouteImport } from './routes/articles.eliminating-data-silos-with-zero-latency-integrations'
import { Route as ArticlesErodedCoimbatoreBengaluruTechLineageRouteImport } from './routes/articles.eroded-coimbatore-bengaluru-tech-lineage'
import { Route as ArticlesPracticalAiAgentsInEnterpriseWorkflowsRouteImport } from './routes/articles.practical-ai-agents-in-enterprise-workflows'
import { Route as ArticlesTheMakeBetterHappenEngineeringFrameworkRouteImport } from './routes/articles.the-make-better-happen-engineering-framework'
import { Route as ArticlesYespCorpGlobalEngineeringAndAiDeliveryRouteImport } from './routes/articles.yesp-corp-global-engineering-and-ai-delivery'
import { Route as PressIndexRouteImport } from './routes/press.index'
import { Route as PressAiAutomationLaunchRouteImport } from './routes/press.ai-automation-launch'
import { Route as PressGlobalExpansionBengaluruRouteImport } from './routes/press.global-expansion-bengaluru'
import { Route as PressMakeBetterHappenInitiativeRouteImport } from './routes/press.make-better-happen-initiative'
import { Route as PressSrinithinSomasundaramKeynoteFutureOfAiRouteImport } from './routes/press.srinithin-somasundaram-keynote-future-of-ai'
import { Route as PressYespCorpGlobalExpansionAndAiInfrastructureRouteImport } from './routes/press.yesp-corp-global-expansion-and-ai-infrastructure'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitelinksRoute = SitelinksRouteImport.update({
  id: '/sitelinks',
  path: '/sitelinks',
  getParentRoute: () => rootRouteImport,
} as any)
const TechExpertiseRoute = TechExpertiseRouteImport.update({
  id: '/tech-expertise',
  path: '/tech-expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute =
  ArticlesBuildingCustomEnterpriseSoftwareVsSaasRouteImport.update({
    id: '/articles/building-custom-enterprise-software-vs-saas',
    path: '/articles/building-custom-enterprise-software-vs-saas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute =
  ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRouteImport.update({
    id: '/articles/eliminating-data-silos-with-zero-latency-integrations',
    path: '/articles/eliminating-data-silos-with-zero-latency-integrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesErodedCoimbatoreBengaluruTechLineageRoute =
  ArticlesErodedCoimbatoreBengaluruTechLineageRouteImport.update({
    id: '/articles/eroded-coimbatore-bengaluru-tech-lineage',
    path: '/articles/eroded-coimbatore-bengaluru-tech-lineage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute =
  ArticlesPracticalAiAgentsInEnterpriseWorkflowsRouteImport.update({
    id: '/articles/practical-ai-agents-in-enterprise-workflows',
    path: '/articles/practical-ai-agents-in-enterprise-workflows',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesTheMakeBetterHappenEngineeringFrameworkRoute =
  ArticlesTheMakeBetterHappenEngineeringFrameworkRouteImport.update({
    id: '/articles/the-make-better-happen-engineering-framework',
    path: '/articles/the-make-better-happen-engineering-framework',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute =
  ArticlesYespCorpGlobalEngineeringAndAiDeliveryRouteImport.update({
    id: '/articles/yesp-corp-global-engineering-and-ai-delivery',
    path: '/articles/yesp-corp-global-engineering-and-ai-delivery',
    getParentRoute: () => rootRouteImport,
  } as any)
const PressIndexRoute = PressIndexRouteImport.update({
  id: '/press/',
  path: '/press/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressAiAutomationLaunchRoute = PressAiAutomationLaunchRouteImport.update({
  id: '/press/ai-automation-launch',
  path: '/press/ai-automation-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const PressGlobalExpansionBengaluruRoute =
  PressGlobalExpansionBengaluruRouteImport.update({
    id: '/press/global-expansion-bengaluru',
    path: '/press/global-expansion-bengaluru',
    getParentRoute: () => rootRouteImport,
  } as any)
const PressMakeBetterHappenInitiativeRoute =
  PressMakeBetterHappenInitiativeRouteImport.update({
    id: '/press/make-better-happen-initiative',
    path: '/press/make-better-happen-initiative',
    getParentRoute: () => rootRouteImport,
  } as any)
const PressSrinithinSomasundaramKeynoteFutureOfAiRoute =
  PressSrinithinSomasundaramKeynoteFutureOfAiRouteImport.update({
    id: '/press/srinithin-somasundaram-keynote-future-of-ai',
    path: '/press/srinithin-somasundaram-keynote-future-of-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PressYespCorpGlobalExpansionAndAiInfrastructureRoute =
  PressYespCorpGlobalExpansionAndAiInfrastructureRouteImport.update({
    id: '/press/yesp-corp-global-expansion-and-ai-infrastructure',
    path: '/press/yesp-corp-global-expansion-and-ai-infrastructure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/founder': typeof FounderRoute
  '/search': typeof SearchRoute
  '/sitelinks': typeof SitelinksRoute
  '/tech-expertise': typeof TechExpertiseRoute
  '/articles/building-custom-enterprise-software-vs-saas': typeof ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute
  '/articles/eliminating-data-silos-with-zero-latency-integrations': typeof ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute
  '/articles/eroded-coimbatore-bengaluru-tech-lineage': typeof ArticlesErodedCoimbatoreBengaluruTechLineageRoute
  '/articles/practical-ai-agents-in-enterprise-workflows': typeof ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute
  '/articles/the-make-better-happen-engineering-framework': typeof ArticlesTheMakeBetterHappenEngineeringFrameworkRoute
  '/articles/yesp-corp-global-engineering-and-ai-delivery': typeof ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute
  '/press/ai-automation-launch': typeof PressAiAutomationLaunchRoute
  '/press/global-expansion-bengaluru': typeof PressGlobalExpansionBengaluruRoute
  '/press/make-better-happen-initiative': typeof PressMakeBetterHappenInitiativeRoute
  '/press/srinithin-somasundaram-keynote-future-of-ai': typeof PressSrinithinSomasundaramKeynoteFutureOfAiRoute
  '/press/yesp-corp-global-expansion-and-ai-infrastructure': typeof PressYespCorpGlobalExpansionAndAiInfrastructureRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/press/': typeof PressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/founder': typeof FounderRoute
  '/search': typeof SearchRoute
  '/sitelinks': typeof SitelinksRoute
  '/tech-expertise': typeof TechExpertiseRoute
  '/articles/building-custom-enterprise-software-vs-saas': typeof ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute
  '/articles/eliminating-data-silos-with-zero-latency-integrations': typeof ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute
  '/articles/eroded-coimbatore-bengaluru-tech-lineage': typeof ArticlesErodedCoimbatoreBengaluruTechLineageRoute
  '/articles/practical-ai-agents-in-enterprise-workflows': typeof ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute
  '/articles/the-make-better-happen-engineering-framework': typeof ArticlesTheMakeBetterHappenEngineeringFrameworkRoute
  '/articles/yesp-corp-global-engineering-and-ai-delivery': typeof ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute
  '/press/ai-automation-launch': typeof PressAiAutomationLaunchRoute
  '/press/global-expansion-bengaluru': typeof PressGlobalExpansionBengaluruRoute
  '/press/make-better-happen-initiative': typeof PressMakeBetterHappenInitiativeRoute
  '/press/srinithin-somasundaram-keynote-future-of-ai': typeof PressSrinithinSomasundaramKeynoteFutureOfAiRoute
  '/press/yesp-corp-global-expansion-and-ai-infrastructure': typeof PressYespCorpGlobalExpansionAndAiInfrastructureRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/press': typeof PressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/founder': typeof FounderRoute
  '/search': typeof SearchRoute
  '/sitelinks': typeof SitelinksRoute
  '/tech-expertise': typeof TechExpertiseRoute
  '/articles/building-custom-enterprise-software-vs-saas': typeof ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute
  '/articles/eliminating-data-silos-with-zero-latency-integrations': typeof ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute
  '/articles/eroded-coimbatore-bengaluru-tech-lineage': typeof ArticlesErodedCoimbatoreBengaluruTechLineageRoute
  '/articles/practical-ai-agents-in-enterprise-workflows': typeof ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute
  '/articles/the-make-better-happen-engineering-framework': typeof ArticlesTheMakeBetterHappenEngineeringFrameworkRoute
  '/articles/yesp-corp-global-engineering-and-ai-delivery': typeof ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute
  '/press/ai-automation-launch': typeof PressAiAutomationLaunchRoute
  '/press/global-expansion-bengaluru': typeof PressGlobalExpansionBengaluruRoute
  '/press/make-better-happen-initiative': typeof PressMakeBetterHappenInitiativeRoute
  '/press/srinithin-somasundaram-keynote-future-of-ai': typeof PressSrinithinSomasundaramKeynoteFutureOfAiRoute
  '/press/yesp-corp-global-expansion-and-ai-infrastructure': typeof PressYespCorpGlobalExpansionAndAiInfrastructureRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/press/': typeof PressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/founder'
    | '/search'
    | '/sitelinks'
    | '/tech-expertise'
    | '/articles/building-custom-enterprise-software-vs-saas'
    | '/articles/eliminating-data-silos-with-zero-latency-integrations'
    | '/articles/eroded-coimbatore-bengaluru-tech-lineage'
    | '/articles/practical-ai-agents-in-enterprise-workflows'
    | '/articles/the-make-better-happen-engineering-framework'
    | '/articles/yesp-corp-global-engineering-and-ai-delivery'
    | '/press/ai-automation-launch'
    | '/press/global-expansion-bengaluru'
    | '/press/make-better-happen-initiative'
    | '/press/srinithin-somasundaram-keynote-future-of-ai'
    | '/press/yesp-corp-global-expansion-and-ai-infrastructure'
    | '/services/$slug'
    | '/articles/'
    | '/press/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/founder'
    | '/search'
    | '/sitelinks'
    | '/tech-expertise'
    | '/articles/building-custom-enterprise-software-vs-saas'
    | '/articles/eliminating-data-silos-with-zero-latency-integrations'
    | '/articles/eroded-coimbatore-bengaluru-tech-lineage'
    | '/articles/practical-ai-agents-in-enterprise-workflows'
    | '/articles/the-make-better-happen-engineering-framework'
    | '/articles/yesp-corp-global-engineering-and-ai-delivery'
    | '/press/ai-automation-launch'
    | '/press/global-expansion-bengaluru'
    | '/press/make-better-happen-initiative'
    | '/press/srinithin-somasundaram-keynote-future-of-ai'
    | '/press/yesp-corp-global-expansion-and-ai-infrastructure'
    | '/services/$slug'
    | '/articles'
    | '/press'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/founder'
    | '/search'
    | '/sitelinks'
    | '/tech-expertise'
    | '/articles/building-custom-enterprise-software-vs-saas'
    | '/articles/eliminating-data-silos-with-zero-latency-integrations'
    | '/articles/eroded-coimbatore-bengaluru-tech-lineage'
    | '/articles/practical-ai-agents-in-enterprise-workflows'
    | '/articles/the-make-better-happen-engineering-framework'
    | '/articles/yesp-corp-global-engineering-and-ai-delivery'
    | '/press/ai-automation-launch'
    | '/press/global-expansion-bengaluru'
    | '/press/make-better-happen-initiative'
    | '/press/srinithin-somasundaram-keynote-future-of-ai'
    | '/press/yesp-corp-global-expansion-and-ai-infrastructure'
    | '/services/$slug'
    | '/articles/'
    | '/press/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FounderRoute: typeof FounderRoute
  SearchRoute: typeof SearchRoute
  SitelinksRoute: typeof SitelinksRoute
  TechExpertiseRoute: typeof TechExpertiseRoute
  ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute: typeof ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute
  ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute: typeof ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute
  ArticlesErodedCoimbatoreBengaluruTechLineageRoute: typeof ArticlesErodedCoimbatoreBengaluruTechLineageRoute
  ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute: typeof ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute
  ArticlesTheMakeBetterHappenEngineeringFrameworkRoute: typeof ArticlesTheMakeBetterHappenEngineeringFrameworkRoute
  ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute: typeof ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute
  PressAiAutomationLaunchRoute: typeof PressAiAutomationLaunchRoute
  PressGlobalExpansionBengaluruRoute: typeof PressGlobalExpansionBengaluruRoute
  PressMakeBetterHappenInitiativeRoute: typeof PressMakeBetterHappenInitiativeRoute
  PressSrinithinSomasundaramKeynoteFutureOfAiRoute: typeof PressSrinithinSomasundaramKeynoteFutureOfAiRoute
  PressYespCorpGlobalExpansionAndAiInfrastructureRoute: typeof PressYespCorpGlobalExpansionAndAiInfrastructureRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  PressIndexRoute: typeof PressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitelinks': {
      id: '/sitelinks'
      path: '/sitelinks'
      fullPath: '/sitelinks'
      preLoaderRoute: typeof SitelinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-expertise': {
      id: '/tech-expertise'
      path: '/tech-expertise'
      fullPath: '/tech-expertise'
      preLoaderRoute: typeof TechExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/building-custom-enterprise-software-vs-saas': {
      id: '/articles/building-custom-enterprise-software-vs-saas'
      path: '/articles/building-custom-enterprise-software-vs-saas'
      fullPath: '/articles/building-custom-enterprise-software-vs-saas'
      preLoaderRoute: typeof ArticlesBuildingCustomEnterpriseSoftwareVsSaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/eliminating-data-silos-with-zero-latency-integrations': {
      id: '/articles/eliminating-data-silos-with-zero-latency-integrations'
      path: '/articles/eliminating-data-silos-with-zero-latency-integrations'
      fullPath: '/articles/eliminating-data-silos-with-zero-latency-integrations'
      preLoaderRoute: typeof ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/eroded-coimbatore-bengaluru-tech-lineage': {
      id: '/articles/eroded-coimbatore-bengaluru-tech-lineage'
      path: '/articles/eroded-coimbatore-bengaluru-tech-lineage'
      fullPath: '/articles/eroded-coimbatore-bengaluru-tech-lineage'
      preLoaderRoute: typeof ArticlesErodedCoimbatoreBengaluruTechLineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/practical-ai-agents-in-enterprise-workflows': {
      id: '/articles/practical-ai-agents-in-enterprise-workflows'
      path: '/articles/practical-ai-agents-in-enterprise-workflows'
      fullPath: '/articles/practical-ai-agents-in-enterprise-workflows'
      preLoaderRoute: typeof ArticlesPracticalAiAgentsInEnterpriseWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/the-make-better-happen-engineering-framework': {
      id: '/articles/the-make-better-happen-engineering-framework'
      path: '/articles/the-make-better-happen-engineering-framework'
      fullPath: '/articles/the-make-better-happen-engineering-framework'
      preLoaderRoute: typeof ArticlesTheMakeBetterHappenEngineeringFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/yesp-corp-global-engineering-and-ai-delivery': {
      id: '/articles/yesp-corp-global-engineering-and-ai-delivery'
      path: '/articles/yesp-corp-global-engineering-and-ai-delivery'
      fullPath: '/articles/yesp-corp-global-engineering-and-ai-delivery'
      preLoaderRoute: typeof ArticlesYespCorpGlobalEngineeringAndAiDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/': {
      id: '/press/'
      path: '/press'
      fullPath: '/press/'
      preLoaderRoute: typeof PressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/ai-automation-launch': {
      id: '/press/ai-automation-launch'
      path: '/press/ai-automation-launch'
      fullPath: '/press/ai-automation-launch'
      preLoaderRoute: typeof PressAiAutomationLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/global-expansion-bengaluru': {
      id: '/press/global-expansion-bengaluru'
      path: '/press/global-expansion-bengaluru'
      fullPath: '/press/global-expansion-bengaluru'
      preLoaderRoute: typeof PressGlobalExpansionBengaluruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/make-better-happen-initiative': {
      id: '/press/make-better-happen-initiative'
      path: '/press/make-better-happen-initiative'
      fullPath: '/press/make-better-happen-initiative'
      preLoaderRoute: typeof PressMakeBetterHappenInitiativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/srinithin-somasundaram-keynote-future-of-ai': {
      id: '/press/srinithin-somasundaram-keynote-future-of-ai'
      path: '/press/srinithin-somasundaram-keynote-future-of-ai'
      fullPath: '/press/srinithin-somasundaram-keynote-future-of-ai'
      preLoaderRoute: typeof PressSrinithinSomasundaramKeynoteFutureOfAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/yesp-corp-global-expansion-and-ai-infrastructure': {
      id: '/press/yesp-corp-global-expansion-and-ai-infrastructure'
      path: '/press/yesp-corp-global-expansion-and-ai-infrastructure'
      fullPath: '/press/yesp-corp-global-expansion-and-ai-infrastructure'
      preLoaderRoute: typeof PressYespCorpGlobalExpansionAndAiInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FounderRoute: FounderRoute,
  SearchRoute: SearchRoute,
  SitelinksRoute: SitelinksRoute,
  TechExpertiseRoute: TechExpertiseRoute,
  ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute:
    ArticlesBuildingCustomEnterpriseSoftwareVsSaasRoute,
  ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute:
    ArticlesEliminatingDataSilosWithZeroLatencyIntegrationsRoute,
  ArticlesErodedCoimbatoreBengaluruTechLineageRoute:
    ArticlesErodedCoimbatoreBengaluruTechLineageRoute,
  ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute:
    ArticlesPracticalAiAgentsInEnterpriseWorkflowsRoute,
  ArticlesTheMakeBetterHappenEngineeringFrameworkRoute:
    ArticlesTheMakeBetterHappenEngineeringFrameworkRoute,
  ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute:
    ArticlesYespCorpGlobalEngineeringAndAiDeliveryRoute,
  PressAiAutomationLaunchRoute: PressAiAutomationLaunchRoute,
  PressGlobalExpansionBengaluruRoute: PressGlobalExpansionBengaluruRoute,
  PressMakeBetterHappenInitiativeRoute: PressMakeBetterHappenInitiativeRoute,
  PressSrinithinSomasundaramKeynoteFutureOfAiRoute:
    PressSrinithinSomasundaramKeynoteFutureOfAiRoute,
  PressYespCorpGlobalExpansionAndAiInfrastructureRoute:
    PressYespCorpGlobalExpansionAndAiInfrastructureRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  PressIndexRoute: PressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
